name: prepared_academy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  # story_view: ^0.14.0
  one_context: ^2.1.0
  like_button: ^2.0.5
  sleek_circular_slider: ^2.0.1
  percent_indicator: ^4.2.2
  customizable_space_bar: ^0.2.0
  # ff_navigation_bar_plus: ^0.1.5
  quickalert: ^1.0.1
  photo_view: ^0.14.0
  story: ^0.8.0
  toggle_switch: ^2.0.1
  syncfusion_flutter_pdfviewer: ^20.3.59
  slide_countdown: ^0.3.4
  html_editor_enhanced: ^2.5.0
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  image_cropper: ^3.0.1
  getwidget: ^3.0.1
  dio: ^4.0.6
  rx_shared_preferences: ^3.0.0
  get_it: ^7.2.0
  dropdown_textfield: ^1.0.7
  dropdown_search: ^5.0.5
  intl_phone_field: ^3.1.0
  animated_snack_bar: ^0.3.0
  # stories_for_flutter: ^1.2.0
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  timeago: ^3.3.0
  # flutter_html: ^3.0.0-alpha.6
  intl: ^0.17.0
  # flutter_easyloading: ^3.0.5
  # video_thumbnail: ^0.5.3
  video_player: ^2.4.10
  # chewie: ^1.3.5
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.2
  flick_video_player: ^0.5.0
  visibility_detector: ^0.3.3
  carousel_slider: ^4.2.1
  expandable_page_view: ^1.0.17
  # flutter_widget_from_html: ^0.8.5
  flutter_html: ^3.0.0-alpha.6
  flutter_widget_from_html_core: ^0.9.0+2
  # webview_flutter: ^3.0.4
  app_version_update: ^2.0.3
  # webviewx_plus: ^0.3.2
  flutter_inappwebview: ^5.7.2+2
  shimmer: ^2.0.0
  fade_shimmer: ^2.2.0
  # curved_labeled_navigation_bar: ^2.0.2
  # vimeo_video_player: ^0.0.6
  url_launcher: ^6.1.7
  flutter_local_notifications: ^12.0.4
  firebase_messaging: ^11.4.4
  firebase_core: ^1.10.0
  firebase_core_platform_interface: 4.5.1
  image_picker_widget: ^2.2.2
  email_validator: ^2.1.17
  pinput: ^2.2.20
  fluttertoast: ^8.1.2
  web_socket_channel: ^2.2.0
  lottie: ^2.1.0
  material_dialogs: ^1.1.4
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  package_rename: ^1.0.0+1



package_rename_config:
  android:
    app_name: 'PreparEd Academy'
    package_name: com.prepared.preparedacademy

  ios:
    app_name: 'PreparEd Academy'
    bundle_name: com.prepared.preparedacademy
    package_name: com.prepared.preparedacademy


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/inclass/
    - assets/logo/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
